const lighterWolfGreen = '#007f99';
const brightGreen = '#05e8b8';

export const textConstants = {
  activation: {
    TITLE: 'Activar cuenta',
    DESCRIPTION: 'Haz click en el botón para activar tu cuenta',
    BUTTON_TEXT: 'Activar cuenta',
    ACTIVATION_SUCCESS: 'Activación exitosa',
  },
  pageTitles: {
    HOME: 'Inicio',
    LOGIN: 'Iniciar sesión',
    CUSTOMERS: 'Clientes',
    ADD_CUSTOMER: 'Agregar cliente',
    EDIT_CUSTOMER: 'Editar cliente',
    CUSTOMER_DETAILS: 'Detalles del cliente',
    PRODUCTS: 'Productos',
    ADD_PRODUCT: 'Agregar producto',
    EDIT_PRODUCT: 'Editar producto',
    PRODUCT_DETAILS: 'Detalles del producto',
    ORDERS: 'Pedidos',
    SALES: 'Ventas',
    NOT_FOUND: 'Página no encontrada',
  },
  login: {
    EMAIL_LABEL: 'Correo Electrónico',
    PASSWORD_LABEL: 'Contraseña',
    MISSING_FIELDS: 'Por favor ingrese correo electrónico y contraseña',
    TITLE: 'Inicia sesión',
    DESCRIPTION: 'Inicia sesión con tu cuenta de inventario de Wolf Snacks',
    LOGIN_ERROR:
      'Hubo un error en el ingreso, por favor revise su conexion e intentelo de nuevo',
    BUTTON_TEXT: 'Ingresar',
    REMEMBER_ME: 'Recordarme en este dispositivo',
    LOGIN_SUCCESS: 'Inicio de sesión exitoso',
    SUBMITTING_TEXT: 'Iniciando sesión...',
    LOGOUT_SUCCESS: 'Cierre de sesión exitoso',
  },
  signup: {
    NAME_LABEL: 'Nombre',
    EMAIL_LABEL: 'Correo Electrónico',
    PASSWORD_LABEL: 'Contraseña',
    CONFIRM_PASSWORD_LABEL: 'Confirmar Contraseña',
    TITLE: 'Crear cuenta',
    DESCRIPTION: 'Crea una nueva cuenta para acceder al inventario de Wolf Snacks',
    BUTTON_TEXT: 'Registrarse',
    SUBMITTING_TEXT: 'Creando cuenta...',
    SIGNUP_SUCCESS: 'Cuenta creada exitosamente. Por favor revisa tu correo para activar tu cuenta',
  },
  user: {
    IS_PERSISTED: 'persisted',
    IS_TEMPORAL: 'temporal',
  },
  addCustomer: {
    TITLE: 'Agregar nuevo cliente',
    ADD_CUSTOMER: 'Agregar cliente',
    ADD_CUSTOMER_SUCCESS: 'Cliente creado exitosamente',
    ADD_CUSTOMER_ERROR: 'Error al agregar cliente',
  },
  addProduct: {
    TITLE: 'Agregar nuevo producto',
    ADD_PRODUCT: 'Agregar producto',
    WARNING_EDIT:
      'Los campos Nombre, Presentacion y Peso no pueden ser editados',
    ADD_PRODUCT_SUCCESS: 'Producto creado exitosamente',
    ADD_PRODUCT_ERROR: 'Error al agregar producto',
  },
  addOrder: {
    TITLE: 'Agregar pedido',
    ADD_ORDER: 'Agregar pedido',
    ADD_PRODUCT: 'Agregar producto',
    ADD_ORDER_SUCCESS: 'Pedido creado exitosamente',
    ADD_ORDER_ERROR: 'Error al agregar pedido',
  },
  addSale: {
    TITLE: 'Agregar venta',
    ADD_SALE: 'Agregar venta',
    ADD_PRODUCT: 'Agregar producto',
    SEARCH_CUSTOMER: 'Buscar cliente',
    ADD_SALE_SUCCESS: 'Venta creada exitosamente',
    ADD_SALE_ERROR: 'Error al agregar venta',
  },
  editCustomer: {
    TITLE: 'Editar cliente',
    EDIT_CUSTOMER_SUCCESS: 'Cliente editado exitosamente',
    EDIT_CUSTOMER_ERROR: 'Error al editar cliente',
  },
  editProduct: {
    TITLE: 'Editar producto',
    EDIT_PRODUCT_SUCCESS: 'Producto editado exitosamente',
    EDIT_PRODUCT_ERROR: 'Error al editar producto',
  },
  editOrder: {
    TITLE: 'Editar pedido',
    EDIT_ORDER_SUCCESS: 'Pedido editado exitosamente',
    EDIT_ORDER_ERROR: 'Error al editar pedido',
  },
  editSale: {
    TITLE: 'Editar venta',
    EDIT_SALE_SUCCESS: 'Venta editada exitosamente',
    EDIT_SALE_ERROR: 'Error al editar venta',
  },
  customer: {
    STORE_NAME: 'Nombre de la tienda',
    NAME: 'Nombre del contacto',
    ADDRESS: 'Dirección',
    EMAIL: 'Correo electrónico',
    PHONE_NUMBER: 'Numero telefónico',
    SECONDARY_PHONE_NUMBER: 'Numero telefónico alternativo',
    LOCALITY: 'Localidad',
    TOWN: 'Barrio',
    ID_NUMBER: 'Cedula o NIT',
    DELETE_CUSTOMER: 'Eliminar cliente',
    EDIT_CUSTOMER: 'Editar cliente',
  },
  product: {
    NAME: 'Nombre',
    PRESENTATION: 'Presentación',
    WEIGHT: 'Peso (g)',
    BASE_PRICE: 'Precio base',
    SELLING_PRICE: 'Precio de venta',
    STOCK: 'Cantidad en inventario',
    DELETE_PRODUCT: 'Eliminar producto',
    EDIT_PRODUCT: 'Editar producto',
  },
  order: {
    TOTAL_PRICE: 'Total',
    ORDER_TOTAL_PRICE: 'Total del pedido',
    PRODUCT_TOTAL_PRICE: 'Total por producto',
    PRICE: 'Precio individual del producto',
    QUANTITY: 'Cantidad',
    PRODUCT: 'Producto',
    PRODUCTS: 'Productos',
    DELETE_ORDER: 'Eliminar pedido',
    EDIT_ORDER: 'Editar pedido',
  },
  sale: {
    TOTAL_PRICE: 'Total',
    SALE_TOTAL_PRICE: 'Total de la venta',
    PRODUCT_TOTAL_PRICE: 'Total por producto',
    PRICE: 'Precio individual del producto',
    OWES: 'Debe',
    IS_THIRTEEN_DOZEN: 'Docena de 13',
    PARTIAL_PAYMENT: 'Abono',
    REMAINING_PAYMENT: 'Saldo',
    QUANTITY: 'Cantidad',
    PRODUCT: 'Producto',
    PRODUCTS: 'Productos',
    CUSTOMER: 'Cliente',
    DELETE_SALE: 'Eliminar venta',
    EDIT_SALE: 'Editar venta',
  },
  customerPage: {
    TITLE: 'Clientes',
    CUSTOMER: 'Cliente',
    DESCRIPTION:
      'Esta es la lista de tus clientes, utiliza los filtros para ayudarte en su busqueda',
    EMPTY_TITLE: 'No se encontraron clientes',
    EMPTY_DESCRIPTION:
      'No existen clientes con los párametros que pusiste en los filtros, si no existe el cliente que buscas puedes agregar uno nuevo con el botón en la parte de abajo',
    DELETE_SUCCESS: 'El cliente ha sido eliminado con exito',
    DELETE_CONFIRMATION_TITLE: 'Eliminar cliente',
    DELETE_CONFIRMATION: 'Confirmas que deseas eliminar el cliente',
    SEARCH_CUSTOMER: 'Buscar cliente',
    SEARCH_CUSTOMER_SUCCESS: 'Cliente encontrado exitosamente',
    SEARCH_CUSTOMER_ERROR: 'Error al buscar cliente',
  },
  productPage: {
    TITLE: 'Productos',
    PRODUCT: 'Producto',
    DESCRIPTION:
      'Esta es la lista de productos, utiliza los filtros para ayudarte en su busqueda',
    EMPTY_TITLE: 'No se encontraron productos',
    EMPTY_DESCRIPTION:
      'No existen productos con los parámetros que pusiste en los filtros, si no existe el producto que buscas puedes agregar uno nuevo con el botón en la parte de abajo',
    DELETE_SUCCESS: 'El producto ha sido eliminado con exito',
    DELETE_CONFIRMATION_TITLE: 'Eliminar producto',
    DELETE_CONFIRMATION: 'Confirmas que deseas eliminar el producto',
    SEARCH_PRODUCT: 'Buscar producto',
    SEARCH_PRODUCT_SUCCESS: 'Producto encontrado exitosamente',
    SEARCH_PRODUCT_ERROR: 'Error al buscar producto',
  },
  orderPage: {
    TITLE: 'Pedidos',
    ORDER: 'Pedido',
    DESCRIPTION:
      'Esta es la lista de pedidos, utiliza los filtros para ayudarte en su busqueda',
    EMPTY_TITLE: 'No se encontraron pedidos',
    EMPTY_DESCRIPTION:
      'No existen pedidos con los parámetros que pusiste en los filtros, si no existe el pedido que buscas puedes agregar uno nuevo con el botón en la parte de abajo',
    DELETE_SUCCESS: 'El pedido ha sido eliminado con exito',
    DELETE_CONFIRMATION_TITLE: 'Eliminar pedido',
    DELETE_CONFIRMATION: 'Confirmas que deseas eliminar el pedido',
    ORDER_DATE: 'Fecha del pedido',
    SEARCH_ORDER_SUCCESS: 'Pedido encontrado exitosamente',
    SEARCH_ORDER_ERROR: 'Error al buscar pedido',
  },
  salePage: {
    TITLE: 'Ventas',
    SALE: 'Venta',
    DESCRIPTION:
      'Esta es la lista de ventas, utiliza los filtros para ayudarte en su busqueda',
    EMPTY_TITLE: 'No se encontraron ventas',
    EMPTY_DESCRIPTION:
      'No existen ventas con los parámetros que pusiste en los filtros, si no existe la venta que buscas puedes agregar una nueva con el botón en la parte de abajo',
    DELETE_SUCCESS: 'La venta ha sido eliminada con exito',
    DELETE_CONFIRMATION_TITLE: 'Eliminar venta',
    DELETE_CONFIRMATION: 'Confirmas que deseas eliminar la venta',
    OWES: 'Debe?',
    IS_THIRTEEN_DOZEN: 'Es docena de 13?',
    SALE_DATE: 'Fecha de la venta',
    SEARCH_SALE_SUCCESS: 'Venta encontrada exitosamente',
    SEARCH_SALE_ERROR: 'Error al buscar venta',
  },
  misc: {
    CUSTOMER_NOT_FOUND: 'Cliente no encontrado',
    CUSTOMER_NOT_FOUND_DESCRIPTION:
      'El cliente que buscas no existe, puedes agregar uno nuevo con el botón en la parte de arriba',
    PRODUCT_NOT_FOUND: 'Producto no encontrado',
    PRODUCT_NOT_FOUND_DESCRIPTION:
      'El producto que buscas no existe, puedes agregar uno nuevo con el botón en la parte de arriba',
    SALE_NOT_FOUND: 'Venta no encontrada',
    SALE_NOT_FOUND_DESCRIPTION:
      'La venta que buscas no existe, puedes agregar una nueva con el botón en la parte de arriba',
    ORDER_NOT_FOUND: 'Pedido no encontrado',
    ORDER_NOT_FOUND_DESCRIPTION:
      'El pedido que buscas no existe, puedes agregar uno nuevo con el botón en la parte de arriba',
    NO_PRODUCT_ID: 'No se proporcionó ID de producto',
    SAVE: 'Guardar',
    EDIT: 'Editar',
    DELETE: 'Eliminar',
    YES: 'Sí',
    NO: 'No',
    ALL: 'Todos',
    DATES: 'Fechas',
    WARNING: 'Advertencia',
    UNITS: 'Unidades',
    DIRECTION: 'Dirección de ordenamiento',
    REMEMBER_ME: 'Recordarme',
    FILTERS: 'Filtros de busqueda',
    FILTERS_TEXT: 'Ingresa los parametros de busqueda que deseas aplicar',
    RESET_FILTERS: 'Limpiar filtros',
    CANCEL: 'Cancelar',
    APPLY: 'Aplicar',
    SEARCH_TERM: 'Término de busqueda',
    ORDER_BY: 'Ordernar la lista por',
    ASCENDING: 'Ascendente',
    DESCENDING: 'Descendente',
    BACK: 'Atras',
    NO_CUSTOMER_ID: 'No se proporcionó un ID de cliente',
    SUBMITTING: 'Enviando...',
    SUBMIT: 'Enviar',
    BUTTON_TEXT: 'Botón',
    LOADING: 'Cargando...',
  },
  navbar: {
    SALES: 'Ventas',
    ORDERS: 'Pedidos',
    CUSTOMERS: 'Clientes',
    PRODUCTS: 'Productos',
    LOGOUT: 'Cerrar sesión',
  },
};

export const errorSuccessConstants = {
  MANDATORY_FIELDS: 'Los siguientes campos son obligatorios:',
  SAVED_CUSTOMER: 'El cliente ha sido guardado exitosamente',
  SAVED_PRODUCT: 'El producto ha sido guardado exitosamente',
  SAVED_ORDER: 'El pedido ha sido guardado exitosamente',
  NO_PRODUCT: 'Todos los productos deben tener los campos diligenciados',
  NO_QUANTITY: 'La cantidad de los productos debe ser mayor a cero',
  NO_EMPTY_PRODUCTS: 'Debe agregar al menos un producto',
  NO_DUPLICATED_PRODUCTS: 'No puedes agregar productos repetidos',
};

export const appConstants = {
  snackbarOptions: {
    position: 'bottom-center',
    style: {
      backgroundColor: brightGreen,
      border: `2px solid ${lighterWolfGreen}`,
      color: lighterWolfGreen,
      fontFamily: 'Roboto, sans-serif',
      fontSize: '1em',
      textAlign: 'center',
      fontWeight: '500',
      zIndex: '20',
    },
    closeStyle: {
      color: lighterWolfGreen,
      fontSize: '1em',
    },
  },
};

export const urlConstants = {
  user: {
    LOGIN: `${import.meta.env.VITE_API_URL}/users/login`,
    LOGOUT: `${import.meta.env.VITE_API_URL}/users/logout`,
  },
  customer: {
    GET_LOCALITIES: `${import.meta.env.VITE_API_URL}/utils/localities`,
    CUSTOMER_URL: `${import.meta.env.VITE_API_URL}/customers`,
  },
  product: {
    GET_PRESENTATIONS: `${import.meta.env.VITE_API_URL}/utils/presentations`,
    GET_PRODUCT_TYPES: `${import.meta.env.VITE_API_URL}/utils/productTypes`,
    PRODUCT_URL: `${import.meta.env.VITE_API_URL}/products`,
  },
  order: {
    ORDER_URL: `${import.meta.env.VITE_API_URL}/orders`,
  },
  sale: {
    SALE_URL: `${import.meta.env.VITE_API_URL}/sales`,
  },
};
